### ISSUE TITLE
现在卡在开头get更新源那一块

### ISSUE THREAD

**Issue by 1391959853** [zhao-zg/jd-login#5]
源是debian的国外源。怎么更换到国内

**Comment by zhao-zg** [comment]
可能是用户账户异常

**Comment by 1391959853** [comment]
oot@iZf8zj20p0xe4ft3fv3hgsZ:~/jdck# docker-compose
 up
[+] Running 1/0
 ⠿ Container jd_autologin  Created            0.0s
Attaching to jd_autologin
jd_autologin  |
jd_autologin  | WARNING: apt does not have a stable
 CLI interface. Use with caution in scripts.
jd_autologin  |
jd_autologin  | Get:1 http://deb.debian.org/debian
bookworm InRelease [151 kB]
jd_autologin  | Get:2 http://deb.debian.org/debian
bookworm-updates InRelease [55.4 kB]
jd_autologin  | Get:3 http://deb.debian.org/debian-
security bookworm-security InRelease [48.0 kB]
jd_autologin  | Get:4 http://deb.debian.org/debian
bookworm/main amd64 Packages [8789 kB]

**Comment by zhao-zg** [comment]
试试
```
version: "3"
services:
  jd_autologin:
    image: zzg1189/jd_login_env:latest
    container_name: jd_login_env
    restart: unless-stopped
    ports:
      - 12345:12345
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
    command: >
      sh -c "rm -rf && wget -O api.py
      https://raw.githubusercontent.com/zhao-zg/jd-login/main/api.py && wget -O
      login.py https://raw.githubusercontent.com/zhao-zg/jd-login/main/login.py
      && python api.py"
networks: {}
```
